// src/album.vue
<template>
	<div class="uk-container">
		<div class="uk-text-lead uk-margin-top">思い出アルバム</div>
		<div class="uk-link-text uk-margin-top"><router-link to="/">トップページ</router-link></div>
		<div class="uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-child-width-1-5@l uk-grid-small uk-text-center" uk-grid>
			<div v-for="(name, i) in names">
				<div class="uk-text-bold uk-margin-top uk-margin-small-bottom">{{ name }}</div>
				<div><img v-bind:id="stickers[i]" v-bind:src="stickers[i]"></div>
			</div>
		</div>
	</div>
</template>
<script>
export default {
	data: function() {
		return {
			names: [
				'アオイ', 'アオイ (編入生)', 'アカリ', 'アカリ (エンジェル)', 'アキノ', 'アヤネ', 'アユミ', 'アユミ (ワンダー)', 'アリサ', 'アン', 'アンナ', 'イオ', 'イノリ', 'イリヤ', 'エリコ', 'カオリ', 'カスミ',
				'カスミ (マジカル)', 'カヤ', 'キャル', 'キョウカ', 'クウカ', 'クウカ (オーエド)', 'クリスティーナ', 'クルミ', 'グレア', 'クロエ', 'コッコロ', 'コッコロ (プリンセス)', 'サレン', 'ジータ', 'シオリ',
				'シオリ (マジカル)', 'シズル', 'シノブ', 'ジュン', 'スズナ', 'スズメ', 'タマキ', 'チエル', 'チカ', 'ツムギ', 'トモ', 'トモ (マジカル)', 'ナナカ', 'ニノン', 'ニノン (オーエド)', 'ネネカ', 'ノゾミ', 'ハツネ',
				'ヒヨリ', 'ペコリーヌ', 'ペコリーヌ (プリンセス)', 'マコト', 'マツリ', 'マヒル', 'マヒル (レンジャー)', 'マホ', 'ミサキ', 'ミサト', 'ミソギ', 'ミツキ', 'ミフユ', 'ミミ', 'ミヤコ', 'ムイミ', 'モニカ',
				'モニカ (マジカル)', 'ユイ', 'ユイ (プリンセス)', 'ユカリ', 'ユキ', 'ユニ', 'ヨリ', 'ヨリ (エンジェル)', 'ラビリスタ', 'リノ', 'リノ (ワンダー)', 'リマ', 'リン', 'リン (レンジャー)', 'ルゥ', 'ルカ', 'ルナ', 'レイ'
			],
			stickers: [
				'./img/aoi_album.webp', './img/aoi_hennyusei_album.webp', './img/akari_album.webp', './img/akari_angel_album.webp', './img/akino_album.webp',
				'./img/ayane_album.webp', './img/ayumi_album.webp', './img/ayumi_wonder_album.webp', './img/arisa_album.webp', './img/an_album.webp', './img/anna_album.webp',
				'./img/io_album.webp', './img/inori_album.webp', './img/iriya_album.webp', './img/eriko_album.webp', './img/kaori_album.webp', './img/kasumi_album.webp',
				'./img/kasumi_magical_album.webp', './img/kaya_album.webp', './img/kyaru_album.webp', './img/kyouka_album.webp', './img/kuuka_album.webp',
				'./img/kuuka_oedo_album.webp', './img/kurisu_album.webp', './img/kurumi_album.webp', './img/gurea_album.webp', './img/kuroe_album.webp', './img/kokkoro_album.webp',
				'./img/kokkoro_princess_album.webp', './img/saren_album.webp', './img/jita_album.webp', './img/shiori_album.webp', './img/shiori_magical_album.webp',
				'./img/shizuru_album.webp', './img/shinobu_album.webp', './img/jun_album.webp', './img/suzuna_album.webp', './img/suzume_album.webp', './img/tamaki_album.webp',
				'./img/chieru_album.webp', './img/chika_album.webp', './img/tsumugi_album.webp', './img/tomo_album.webp', './img/tomo_magical_album.webp', './img/nanaka_album.webp','./img/ninon_album.webp',
				'./img/ninon_oedo_album.webp', './img/neneka_album.webp', './img/nozomi_album.webp', './img/hatsune_album.webp', './img/hiyori_album.webp', './img/peko_album.webp',
				'./img/peko_princess_album.webp', './img/makoto_album.webp', './img/matsuri_album.webp', './img/mahiru_album.webp', './img/mahiru_ranger_album.webp',
				'./img/maho_album.webp', './img/misaki_album.webp', './img/misato_album.webp', './img/misogi_album.webp', './img/mitsuki_album.webp', './img/mihuyu_album.webp',
				'./img/mimi_album.webp', './img/miyako_album.webp', './img/muimi_album.webp', './img/monika_album.webp', './img/monika_magical_album.webp', './img/yui_album.webp',
				'./img/yui_princess_album.webp', './img/yukari_album.webp', './img/yuki_album.webp', './img/yuni_album.webp', './img/yori_album.webp', './img/yori_angel_album.webp',
				'./img/rabirisuta_album.webp', './img/rino_album.webp', './img/rino_wonder_album.webp', './img/rima_album.webp', './img/rin_album.webp',
				'./img/rin_ranger_album.webp', './img/ruu_album.webp', './img/ruka_album.webp', './img/runa_album.webp', './img/rei_album.webp'
			]
		}
	},
}
</script>
<style scoped>
</style>

// pages/album.tsx
import type { NextPage } from 'next'
import Image from 'next/image'

const Album: NextPage = () => {
  const stickers = [
    { name: 'アオイ', path: '/img/album/aoi.webp', width: 512, height: 383 },
    { name: 'アオイ (作業服)', path: '/img/album/aoi_work_clothes.webp', width: 512, height: 383 },
    { name: 'アオイ (編入生)', path: '/img/album/aoi_hennyusei.webp', width: 512, height: 383 },
    { name: 'アカリ', path: '/img/album/akari.webp', width: 512, height: 383 },
    { name: 'アカリ (エンジェル)', path: '/img/album/akari_angel.webp', width: 512, height: 383 },
    { name: 'アキノ', path: '/img/album/akino.webp', width: 512, height: 383 },
    { name: 'アヤネ', path: '/img/album/ayane.webp', width: 512, height: 383 },
    { name: 'アユミ', path: '/img/album/ayumi.webp', width: 512, height: 383 },
    { name: 'アユミ (ワンダー)', path: '/img/album/ayumi_wonder.webp', width: 512, height: 383 },
    { name: 'アリサ', path: '/img/album/arisa.webp', width: 512, height: 383 },
    { name: 'アン', path: '/img/album/an.webp', width: 512, height: 383 },
    { name: 'アンナ', path: '/img/album/anna.webp', width: 512, height: 383 },
    { name: 'イオ', path: '/img/album/io.webp', width: 512, height: 383 },
    { name: 'イオ (ノワール)', path: '/img/album/io_noir.webp', width: 512, height: 383 },
    { name: 'イノリ', path: '/img/album/inori.webp', width: 512, height: 383 },
    { name: 'イノリ (タイムトラベル)', path: '/img/album/inori_timetravel.webp', width: 512, height: 383 },
    { name: 'イリヤ', path: '/img/album/iriya.webp', width: 512, height: 383 },
    { name: 'エリコ', path: '/img/album/eriko.webp', width: 512, height: 383 },
    { name: 'カオリ', path: '/img/album/kaori.webp', width: 512, height: 383 },
    { name: 'カスミ', path: '/img/album/kasumi.webp', width: 512, height: 383 },
    { name: 'カスミ (マジカル)', path: '/img/album/kasumi_magical.webp', width: 512, height: 383 },
    { name: 'カヤ', path: '/img/album/kaya.webp', width: 512, height: 383 },
    { name: 'カヤ (タイムトラベル)', path: '/img/album/kaya_timetravel.webp', width: 512, height: 383 },
    { name: 'カリン', path: '/img/album/karin.webp', width: 512, height: 383 },
    { name: 'キャル', path: '/img/album/kyaru.webp', width: 512, height: 383 },
    { name: 'キャル (プリンセス)', path: '/img/album/kyaru_princess.webp', width: 512, height: 383 },
    { name: 'キョウカ', path: '/img/album/kyouka.webp', width: 512, height: 383 },
    { name: 'クウカ', path: '/img/album/kuuka.webp', width: 512, height: 383 },
    { name: 'クウカ (オーエド)', path: '/img/album/kuuka_oedo.webp', width: 512, height: 383 },
    { name: 'クリスティーナ', path: '/img/album/kurisu.webp', width: 512, height: 383 },
    { name: 'クルミ', path: '/img/album/kurumi.webp', width: 512, height: 383 },
    { name: 'グレア', path: '/img/album/gurea.webp', width: 512, height: 383 },
    { name: 'クレジッタ', path: '/img/album/kurejitta.webp', width: 512, height: 383 },
    { name: 'クロエ', path: '/img/album/kuroe.webp', width: 512, height: 383 },
    { name: 'クロエ (聖学祭)', path: '/img/album/kuroe_seigakusai.webp', width: 512, height: 383 },
    { name: 'コッコロ', path: '/img/album/kokkoro.webp', width: 512, height: 383 },
    { name: 'コッコロ (プリンセス)', path: '/img/album/kokkoro_princess.webp', width: 512, height: 383 },
    { name: 'サレン', path: '/img/album/saren.webp', width: 512, height: 383 },
    { name: 'ジータ', path: '/img/album/jita.webp', width: 512, height: 383 },
    { name: 'シェフィ', path: '/img/album/sheffi.webp', width: 512, height: 383 },
    { name: 'シオリ', path: '/img/album/shiori.webp', width: 512, height: 383 },
    { name: 'シオリ (マジカル)', path: '/img/album/shiori_magical.webp', width: 512, height: 383 },
    { name: 'シズル', path: '/img/album/shizuru.webp', width: 512, height: 383 },
    { name: 'シノブ', path: '/img/album/shinobu.webp', width: 512, height: 383 },
    { name: 'ジュン', path: '/img/album/jun.webp', width: 512, height: 383 },
    { name: 'スズナ', path: '/img/album/suzuna.webp', width: 512, height: 383 },
    { name: 'スズメ', path: '/img/album/suzume.webp', width: 512, height: 383 },
    { name: 'タマキ', path: '/img/album/tamaki.webp', width: 512, height: 383 },
    { name: 'タマキ (作業服)', path: '/img/album/tamaki_work_clothes.webp', width: 512, height: 383 },
    { name: 'チエル', path: '/img/album/chieru.webp', width: 512, height: 383 },
    { name: 'チエル (聖学祭)', path: '/img/album/chieru_seigakusai.webp', width: 512, height: 383 },
    { name: 'チカ', path: '/img/album/chika.webp', width: 512, height: 383 },
    { name: 'ツムギ', path: '/img/album/tsumugi.webp', width: 512, height: 383 },
    { name: 'トモ', path: '/img/album/tomo.webp', width: 512, height: 383 },
    { name: 'トモ (マジカル)', path: '/img/album/tomo_magical.webp', width: 512, height: 383 },
    { name: 'ナナカ', path: '/img/album/nanaka.webp', width: 512, height: 383 },
    { name: 'ニノン', path: '/img/album/ninon.webp', width: 512, height: 383 },
    { name: 'ニノン (オーエド)', path: '/img/album/ninon_oedo.webp', width: 512, height: 383 },
    { name: 'ネネカ', path: '/img/album/neneka.webp', width: 512, height: 383 },
    { name: 'ノゾミ', path: '/img/album/nozomi.webp', width: 512, height: 383 },
    { name: 'ハツネ', path: '/img/album/hatsune.webp', width: 512, height: 383 },
    { name: 'ハツネ&シオリ', path: '/img/album/hatsune_and_shiori.webp', width: 512, height: 383 },
    { name: 'ヒヨリ', path: '/img/album/hiyori.webp', width: 512, height: 383 },
    { name: 'ヒヨリ (プリンセス)', path: '/img/album/hiyori_princess.webp', width: 512, height: 383 },
    { name: 'ペコリーヌ', path: '/img/album/peko.webp', width: 512, height: 383 },
    { name: 'ペコリーヌ (プリンセス)', path: '/img/album/peko_princess.webp', width: 512, height: 383 },
    { name: 'ホマレ', path: '/img/album/homare.webp', width: 512, height: 383 },
    { name: 'マコト', path: '/img/album/makoto.webp', width: 512, height: 383 },
    { name: 'マコト (シンデレラ)', path: '/img/album/makoto_cinderella.webp', width: 512, height: 383 },
    { name: 'マツリ', path: '/img/album/matsuri.webp', width: 512, height: 383 },
    { name: 'マヒル', path: '/img/album/mahiru.webp', width: 512, height: 383 },
    { name: 'マヒル (レンジャー)', path: '/img/album/mahiru_ranger.webp', width: 512, height: 383 },
    { name: 'マホ', path: '/img/album/maho.webp', width: 512, height: 383 },
    { name: 'マホ (シンデレラ)', path: '/img/album/maho_cinderella.webp', width: 512, height: 383 },
    { name: 'ミサキ', path: '/img/album/misaki.webp', width: 512, height: 383 },
    { name: 'ミサト', path: '/img/album/misato.webp', width: 512, height: 383 },
    { name: 'ミソギ', path: '/img/album/misogi.webp', width: 512, height: 383 },
    { name: 'ミツキ', path: '/img/album/mitsuki.webp', width: 512, height: 383 },
    { name: 'ミツキ (オーエド)', path: '/img/album/mitsuki_oedo.webp', width: 512, height: 383 },
    { name: 'ミフユ', path: '/img/album/mihuyu.webp', width: 512, height: 383 },
    { name: 'ミフユ (作業服)', path: '/img/album/mihuyu_work_clothes.webp', width: 512, height: 383 },
    { name: 'ミミ', path: '/img/album/mimi.webp', width: 512, height: 383 },
    { name: 'ミヤコ', path: '/img/album/miyako.webp', width: 512, height: 383 },
    { name: 'ムイミ', path: '/img/album/muimi.webp', width: 512, height: 383 },
    { name: 'モニカ', path: '/img/album/monika.webp', width: 512, height: 383 },
    { name: 'モニカ (マジカル)', path: '/img/album/monika_magical.webp', width: 512, height: 383 },
    { name: 'ユイ', path: '/img/album/yui.webp', width: 512, height: 383 },
    { name: 'ユイ (プリンセス)', path: '/img/album/yui_princess.webp', width: 512, height: 383 },
    { name: 'ユカリ', path: '/img/album/yukari.webp', width: 512, height: 383 },
    { name: 'ユキ', path: '/img/album/yuki.webp', width: 512, height: 383 },
    { name: 'ユキ (オーエド)', path: '/img/album/yuki_oedo.webp', width: 512, height: 383 },
    { name: 'ユニ', path: '/img/album/yuni.webp', width: 512, height: 383 },
    { name: 'ヨリ', path: '/img/album/yori.webp', width: 512, height: 383 },
    { name: 'ヨリ (エンジェル)', path: '/img/album/yori_angel.webp', width: 512, height: 383 },
    { name: 'ラビリスタ', path: '/img/album/rabirisuta.webp', width: 512, height: 383 },
    { name: 'リノ', path: '/img/album/rino.webp', width: 512, height: 383 },
    { name: 'リノ (ワンダー)', path: '/img/album/rino_wonder.webp', width: 512, height: 383 },
    { name: 'リマ', path: '/img/album/rima.webp', width: 512, height: 383 },
    { name: 'リマ (シンデレラ)', path: '/img/album/rima_cinderella.webp', width: 512, height: 383 },
    { name: 'リン', path: '/img/album/rin.webp', width: 512, height: 383 },
    { name: 'リン (レンジャー)', path: '/img/album/rin_ranger.webp', width: 512, height: 383 },
    { name: 'ルゥ', path: '/img/album/ruu.webp', width: 512, height: 383 },
    { name: 'ルカ', path: '/img/album/ruka.webp', width: 512, height: 383 },
    { name: 'ルナ', path: '/img/album/runa.webp', width: 512, height: 383 },
    { name: 'レイ', path: '/img/album/rei.webp', width: 512, height: 383 },
    { name: 'レイ (プリンセス)', path: '/img/album/rei_princess.webp', width: 512, height: 383 },
  ];

  return (
    <div className="container">
      <div className="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5 row-cols-xl-6 text-center">
      {
        stickers.map(value => (
          <div className="col mb-3" key={ value.path }>
            <div className="mb-1">{ value.name }</div>
            <Image src={ value.path } width={ value.width } height={ value.height } alt={ value.name } />
          </div>
        ))
      }
      </div>
    </div>
  )
}

export default Album
