// pages/angel.tsx
import type { NextPage } from 'next'
import Image from 'next/image'

const Angel: NextPage = () => {
  const stickers = [
    { name: '次世代へ継承すべき新言語', path: '/img/angel/chieru.webp', width: 800, height: 680 },
    { name: '私はとても作文が苦手です', path: '/img/angel/kuroe.webp', width: 800, height: 680 },
    { name: '飛翔へと至るまで', path: '/img/angel/yuni.webp', width: 800, height: 680 },
    { name: '閃きましたわ!', path: '/img/angel/akino.webp', width: 800, height: 680 },
    { name: '組み立てにゃ!', path: '/img/angel/tamaki.webp', width: 800, height: 680 },
    { name: '私こんなの書いたっけ…?', path: '/img/angel/yukari.webp', width: 800, height: 680 },
    { name: 'このままにしておけないわ', path: '/img/angel/mihuyu.webp', width: 800, height: 680 },
    { name: '特別講座を終えて', path: '/img/angel/mercurius.webp', width: 800, height: 680 },
    { name: '考察', path: '/img/angel/nakayoshix1.webp', width: 800, height: 680 },
    { name: '試作機完成', path: '/img/angel/nakayoshix2.webp', width: 800, height: 680 },
    { name: '最終工程', path: '/img/angel/nakayoshix3.webp', width: 800, height: 680 },
  ];
  return (
    <div className="container">
      <div className="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5 row-cols-xl-6 text-center">
      {
        stickers.map(value => (
          <div className="col mb-3" key={ value.path }>
            <div className="mb-1">{ value.name }</div>
            <Image src={ value.path } width={ value.width } height={ value.height } alt={ value.name } />
          </div>
        ))
      }
      </div>
    </div>
  )
}

export default Angel

// src/angel.vue
<template>
	<div class="uk-container">
		<div class="uk-text-lead uk-margin-top">授けの財団と聖なる学舎の異端児</div>
		<div class="uk-margin-top uk-link-muted"><router-link to="/">トップページ</router-link></div>
		<div class="uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-child-width-1-5@l uk-grid-small uk-text-center" uk-grid>
			<div v-for="(name, i) in names">
				<div class="uk-text-bold uk-margin-top uk-margin-small-bottom">{{ name }}</div>
				<div><img v-bind:id="stickers[i]" v-bind:src="stickers[i]"></div>
			</div>
		</div>
	</div>
</template>
<script>
export default {
	data: function() {
		return {
			names: [
				'次世代へ継承すべき新言語',
				'私はとても作文が苦手です',
				'飛翔へと至るまで',
				'閃きましたわ!',
				'組み立てにゃ!',
				'私こんなの書いたっけ…?',
				'このままにしておけないわ',
				'特別講座を終えて',
				'考察',
				'試作機完成',
				'最終工程'
			],
			stickers: [
				'./img/chieru_foundation.webp',
				'./img/kuroe_foundation.webp',
				'./img/yuni_foundation.webp',
				'./img/akino_foundation.webp',
				'./img/tamaki_foundation.webp',
				'./img/yukari_foundation.webp',
				'./img/mihuyu_foundation.webp',
				'./img/mercurius_foundation.webp',
				'./img/nakayoshix1_foundation.webp',
				'./img/nakayoshix2_foundation.webp',
				'./img/nakayoshix3_foundation.webp'
			]
		}
	},
}
</script>
<style scoped>
</style>
