// pages/shiritori.tsx
import type { NextPage } from "next";

export const stickers = [
  {
    name: "リンゴ",
    path: "/img/shiritori/apple.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ゴリラ",
    path: "/img/shiritori/gorilla.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ラッパ",
    path: "/img/shiritori/trumpet.webp",
    width: 120,
    height: 120,
  },
  {
    name: "パイナップル",
    path: "/img/shiritori/pineapple.webp",
    width: 120,
    height: 120,
  },
  { name: "ルビー", path: "/img/shiritori/ruby.webp", width: 120, height: 120 },
  {
    name: "ビールっぽいもの",
    path: "/img/shiritori/beer.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ゆみや",
    path: "/img/shiritori/bow_and_row.webp",
    width: 120,
    height: 120,
  },
  { name: "おんぷ", path: "/img/shiritori/note.webp", width: 120, height: 120 },
  {
    name: "えのぐ",
    path: "/img/shiritori/paint.webp",
    width: 120,
    height: 120,
  },
  { name: "けん", path: "/img/shiritori/sword.webp", width: 120, height: 120 },
  {
    name: "めがね",
    path: "/img/shiritori/glasses.webp",
    width: 120,
    height: 120,
  },
  {
    name: "むしめがね",
    path: "/img/shiritori/loupe.webp",
    width: 120,
    height: 120,
  },
  { name: "にく", path: "/img/shiritori/meat.webp", width: 120, height: 120 },
  { name: "つき", path: "/img/shiritori/moon.webp", width: 120, height: 120 },
  {
    name: "こうもり",
    path: "/img/shiritori/bat.webp",
    width: 120,
    height: 120,
  },
  { name: "とり", path: "/img/shiritori/bird.webp", width: 120, height: 120 },
  { name: "くつ", path: "/img/shiritori/shoes.webp", width: 120, height: 120 },
  { name: "ねこ", path: "/img/shiritori/cat.webp", width: 120, height: 120 },
  {
    name: "きんぎょ",
    path: "/img/shiritori/goldfish.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ねずみ",
    path: "/img/shiritori/mouse.webp",
    width: 120,
    height: 120,
  },
  { name: "たまご", path: "/img/shiritori/egg.webp", width: 120, height: 120 },
  { name: "ふね", path: "/img/shiritori/ship.webp", width: 120, height: 120 },
  {
    name: "ぎゅうにゅう",
    path: "/img/shiritori/milk.webp",
    width: 120,
    height: 120,
  },
  {
    name: "チョコレート",
    path: "/img/shiritori/chocolate.webp",
    width: 120,
    height: 120,
  },
  {
    name: "どんぐり",
    path: "/img/shiritori/acorn.webp",
    width: 120,
    height: 120,
  },
  {
    name: "いちご",
    path: "/img/shiritori/strawberry.webp",
    width: 120,
    height: 120,
  },
  { name: "とら", path: "/img/shiritori/tiger.webp", width: 120, height: 120 },
  {
    name: "ぬいぐるみ",
    path: "/img/shiritori/stuffed_animal.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ばくだん",
    path: "/img/shiritori/bomb.webp",
    width: 120,
    height: 120,
  },
  {
    name: "すいか",
    path: "/img/shiritori/watermelon.webp",
    width: 120,
    height: 120,
  },
  { name: "うま", path: "/img/shiritori/horse.webp", width: 120, height: 120 },
  { name: "いす", path: "/img/shiritori/chair.webp", width: 120, height: 120 },
  { name: "うみ", path: "/img/shiritori/sea.webp", width: 120, height: 120 },
  {
    name: "やどかり",
    path: "/img/shiritori/hermit_crab.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ふえ",
    path: "/img/shiritori/whistle.webp",
    width: 120,
    height: 120,
  },
  { name: "ほん", path: "/img/shiritori/book.webp", width: 120, height: 120 },
  { name: "さかな", path: "/img/shiritori/fish.webp", width: 120, height: 120 },
  { name: "ツリー", path: "/img/shiritori/tree.webp", width: 120, height: 120 },
  { name: "あめ", path: "/img/shiritori/candy.webp", width: 120, height: 120 },
  {
    name: "ハンマー",
    path: "/img/shiritori/hammer.webp",
    width: 120,
    height: 120,
  },
  { name: "ほし", path: "/img/shiritori/star.webp", width: 120, height: 120 },
  { name: "ぼうし", path: "/img/shiritori/hat.webp", width: 120, height: 120 },
  { name: "カップ", path: "/img/shiritori/cup.webp", width: 120, height: 120 },
  { name: "いぬ", path: "/img/shiritori/dog.webp", width: 120, height: 120 },
  { name: "はた", path: "/img/shiritori/flag.webp", width: 120, height: 120 },
  { name: "ケーキ", path: "/img/shiritori/cake.webp", width: 120, height: 120 },
  {
    name: "マイク",
    path: "/img/shiritori/microphone.webp",
    width: 120,
    height: 120,
  },
  {
    name: "くちべに",
    path: "/img/shiritori/lipstick.webp",
    width: 120,
    height: 120,
  },
  { name: "もち", path: "/img/shiritori/mochi.webp", width: 120, height: 120 },
  {
    name: "ようせい",
    path: "/img/shiritori/fairy.webp",
    width: 120,
    height: 120,
  },
  {
    name: "かさ",
    path: "/img/shiritori/umbrella.webp",
    width: 120,
    height: 120,
  },
  {
    name: "さいころ",
    path: "/img/shiritori/dice.webp",
    width: 120,
    height: 120,
  },
  {
    name: "てがみ",
    path: "/img/shiritori/letter.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ブドウ",
    path: "/img/shiritori/grape.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ひつじ",
    path: "/img/shiritori/sheep.webp",
    width: 120,
    height: 120,
  },
  { name: "とうふ", path: "/img/shiritori/tofu.webp", width: 120, height: 120 },
  { name: "あひる", path: "/img/shiritori/duck.webp", width: 120, height: 120 },
  {
    name: "とんぼ",
    path: "/img/shiritori/dragonfly.webp",
    width: 120,
    height: 120,
  },
  { name: "はっぱ", path: "/img/shiritori/leaf.webp", width: 120, height: 120 },
  { name: "ゆびわ", path: "/img/shiritori/ring.webp", width: 120, height: 120 },
  { name: "なわ", path: "/img/shiritori/rope.webp", width: 120, height: 120 },
  { name: "たて", path: "/img/shiritori/shield.webp", width: 120, height: 120 },
  {
    name: "おかね",
    path: "/img/shiritori/money.webp",
    width: 120,
    height: 120,
  },
  {
    name: "プリンアラモード",
    path: "/img/shiritori/pudding.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ネックレス",
    path: "/img/shiritori/necklace.webp",
    width: 120,
    height: 120,
  },
  {
    name: "いなほ",
    path: "/img/shiritori/rice_ear.webp",
    width: 120,
    height: 120,
  },
  {
    name: "しょうゆ",
    path: "/img/shiritori/soy_sauce.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ベルトコンベア",
    path: "/img/shiritori/belt_conveyor.webp",
    width: 120,
    height: 120,
  },
  {
    name: "シャンデリア",
    path: "/img/shiritori/chandelier.webp",
    width: 120,
    height: 120,
  },
  { name: "しお", path: "/img/shiritori/salt.webp", width: 120, height: 120 },
  {
    name: "うずしお",
    path: "/img/shiritori/whirlpool.webp",
    width: 120,
    height: 120,
  },
  {
    name: "つりざお",
    path: "/img/shiritori/rod.webp",
    width: 120,
    height: 120,
  },
  { name: "なべ", path: "/img/shiritori/pot.webp", width: 120, height: 120 },
  {
    name: "シーソー",
    path: "/img/shiritori/seesaw.webp",
    width: 120,
    height: 120,
  },
  { name: "ふで", path: "/img/shiritori/brush.webp", width: 120, height: 120 },
  {
    name: "きんトレ",
    path: "/img/shiritori/work_out.webp",
    width: 120,
    height: 120,
  },
  {
    name: "おばけ",
    path: "/img/shiritori/ghost.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ヒヨリ",
    path: "/img/shiritori/hiyori.webp",
    width: 120,
    height: 120,
  },
  { name: "ユイ", path: "/img/shiritori/yui.webp", width: 120, height: 120 },
  { name: "レイ", path: "/img/shiritori/rei.webp", width: 120, height: 120 },
  {
    name: "ミソギ",
    path: "/img/shiritori/misogi.webp",
    width: 120,
    height: 120,
  },
  {
    name: "マツリ",
    path: "/img/shiritori/matsuri.webp",
    width: 120,
    height: 120,
  },
  {
    name: "アカリ",
    path: "/img/shiritori/akari.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ミヤコ",
    path: "/img/shiritori/miyako.webp",
    width: 120,
    height: 120,
  },
  { name: "ユキ", path: "/img/shiritori/yuki.webp", width: 120, height: 120 },
  { name: "アンナ", path: "/img/shiritori/anna.webp", width: 120, height: 120 },
  { name: "マホ", path: "/img/shiritori/maho.webp", width: 120, height: 120 },
  { name: "リノ", path: "/img/shiritori/rino.webp", width: 120, height: 120 },
  {
    name: "ハツネ",
    path: "/img/shiritori/hatsune.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ナナカ",
    path: "/img/shiritori/nanaka.webp",
    width: 120,
    height: 120,
  },
  {
    name: "カスミ",
    path: "/img/shiritori/kasumi.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ミサト",
    path: "/img/shiritori/misato.webp",
    width: 120,
    height: 120,
  },
  {
    name: "スズナ",
    path: "/img/shiritori/suzuna.webp",
    width: 120,
    height: 120,
  },
  {
    name: "カオリ",
    path: "/img/shiritori/kaori.webp",
    width: 120,
    height: 120,
  },
  { name: "イオ", path: "/img/shiritori/io.webp", width: 120, height: 120 },
  { name: "ミミ", path: "/img/shiritori/mimi.webp", width: 120, height: 120 },
  {
    name: "クルミ",
    path: "/img/shiritori/kurumi.webp",
    width: 120,
    height: 120,
  },
  { name: "ヨリ", path: "/img/shiritori/yori.webp", width: 120, height: 120 },
  {
    name: "アヤネ",
    path: "/img/shiritori/ayane.webp",
    width: 120,
    height: 120,
  },
  {
    name: "スズメ",
    path: "/img/shiritori/suzume.webp",
    width: 120,
    height: 120,
  },
  { name: "リン", path: "/img/shiritori/rin.webp", width: 120, height: 120 },
  {
    name: "エリコ",
    path: "/img/shiritori/eriko.webp",
    width: 120,
    height: 120,
  },
  {
    name: "サレン",
    path: "/img/shiritori/saren.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ノゾミ",
    path: "/img/shiritori/nozomi.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ニノン",
    path: "/img/shiritori/ninon.webp",
    width: 120,
    height: 120,
  },
  {
    name: "シノブ",
    path: "/img/shiritori/shinobu.webp",
    width: 120,
    height: 120,
  },
  {
    name: "アキノ",
    path: "/img/shiritori/akino.webp",
    width: 120,
    height: 120,
  },
  {
    name: "マヒル",
    path: "/img/shiritori/mahiru.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ユカリ",
    path: "/img/shiritori/yukari.webp",
    width: 120,
    height: 120,
  },
  {
    name: "キョウカ",
    path: "/img/shiritori/kyouka.webp",
    width: 120,
    height: 120,
  },
  { name: "トモ", path: "/img/shiritori/tomo.webp", width: 120, height: 120 },
  {
    name: "シオリ",
    path: "/img/shiritori/shiori.webp",
    width: 120,
    height: 120,
  },
  { name: "アオイ", path: "/img/shiritori/aoi.webp", width: 120, height: 120 },
  { name: "チカ", path: "/img/shiritori/chika.webp", width: 120, height: 120 },
  {
    name: "マコト",
    path: "/img/shiritori/makoto.webp",
    width: 120,
    height: 120,
  },
  {
    name: "イリヤ",
    path: "/img/shiritori/iriya.webp",
    width: 120,
    height: 120,
  },
  {
    name: "クウカ",
    path: "/img/shiritori/kuuka.webp",
    width: 120,
    height: 120,
  },
  {
    name: "タマキ",
    path: "/img/shiritori/tamaki.webp",
    width: 120,
    height: 120,
  },
  { name: "ジュン", path: "/img/shiritori/jun.webp", width: 120, height: 120 },
  {
    name: "ミフユ",
    path: "/img/shiritori/mihuyu.webp",
    width: 120,
    height: 120,
  },
  {
    name: "シズル",
    path: "/img/shiritori/shizuru.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ミサキ",
    path: "/img/shiritori/misaki.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ミツキ",
    path: "/img/shiritori/mitsuki.webp",
    width: 120,
    height: 120,
  },
  { name: "リマ", path: "/img/shiritori/rima.webp", width: 120, height: 120 },
  {
    name: "モニカ",
    path: "/img/shiritori/monika.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ツムギ",
    path: "/img/shiritori/tsumugi.webp",
    width: 120,
    height: 120,
  },
  {
    name: "アユミ",
    path: "/img/shiritori/ayumi.webp",
    width: 120,
    height: 120,
  },
  { name: "ルカ", path: "/img/shiritori/ruka.webp", width: 120, height: 120 },
  { name: "ジータ", path: "/img/shiritori/jita.webp", width: 120, height: 120 },
  {
    name: "ペコリーヌ",
    path: "/img/shiritori/peko.webp",
    width: 120,
    height: 120,
  },
  {
    name: "コッコロ",
    path: "/img/shiritori/kokkoro.webp",
    width: 120,
    height: 120,
  },
  {
    name: "キャル",
    path: "/img/shiritori/kyaru.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ムイミ",
    path: "/img/shiritori/muimi.webp",
    width: 120,
    height: 120,
  },
  {
    name: "アリサ",
    path: "/img/shiritori/arisa.webp",
    width: 120,
    height: 120,
  },
  {
    name: "ネネカ",
    path: "/img/shiritori/neneka.webp",
    width: 120,
    height: 120,
  },
  {
    name: "クリスティーナ",
    path: "/img/shiritori/kurisu.webp",
    width: 120,
    height: 120,
  },
  {
    name: "イノリ",
    path: "/img/shiritori/inori.webp",
    width: 120,
    height: 120,
  },
  { name: "カヤ", path: "/img/shiritori/kaya.webp", width: 120, height: 120 },
  {
    name: "ホマレ",
    path: "/img/shiritori/homare.webp",
    width: 120,
    height: 120,
  },
  {
    name: "クロエ",
    path: "/img/shiritori/kuroe.webp",
    width: 120,
    height: 120,
  },
  {
    name: "チエル",
    path: "/img/shiritori/chieru.webp",
    width: 120,
    height: 120,
  },
  { name: "ユニ", path: "/img/shiritori/yuni.webp", width: 120, height: 120 },
];

const Shiritori: NextPage = () => {
  return (
    <div className="container">
      <div className="row gy-3 row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-5 row-cols-xl-6 text-center">
        {stickers.map((value) => (
          <div className="col" key={value.path}>
            <div className="mb-1">{value.name}</div>
            <img
              className="img-fluid"
              src={value.path}
              width={value.width}
              height={value.height}
              alt={value.name}
            />
          </div>
        ))}
      </div>
    </div>
  );
};

export default Shiritori;

// src/shiritori.vue
<template>
	<div class="uk-container">
		<div class="uk-text-lead uk-margin-top">しりとりドラゴンズ</div>
		<div class="uk-margin-top uk-link-muted"><router-link to="/">トップページ</router-link></div>
		<div class="uk-child-width-1-2 uk-child-width-1-3@s uk-child-width-1-4@m uk-child-width-1-5@l uk-grid-small uk-text-center" uk-grid>
			<div v-for="(name, i) in names">
				<div class="uk-text-bold uk-margin-top uk-margin-small-bottom">{{ name }}</div>
				<div><img v-bind:id="stickers[i]" v-bind:src="stickers[i]"></div>
			</div>
		</div>
	</div>
</template>
<script>
export default {
	data: function() {
		return {
			names: [
				'リンゴ', 'ゴリラ', 'ラッパ', 'パイナップル', 'ルビー', 'ビールっぽいもの', 'ゆみや', 'おんぷ', 'えのぐ', 'けん', 'めがね', 'むしめがね', 'にく', 'つき', 'こうもり', 'とり', 'くつ', 'ねこ', 'きんぎょ', 'ねずみ',
				'たまご', 'ふね', 'ぎゅうにゅう', 'チョコレート', 'どんぐり', 'いちご', 'とら', 'ぬいぐるみ', 'ばくだん', 'すいか', 'うま', 'いす', 'うみ', 'やどかり', 'ふえ', 'ほん', 'さかな', 'ツリー', 'あめ', 'ハンマー',
				'ほし', 'ぼうし', 'カップ', 'いぬ', 'はた', 'ケーキ', 'マイク', 'くちべに', 'もち', 'ようせい', 'かさ', 'さいころ', 'てがみ', 'ブドウ', 'ひつじ', 'とうふ', 'あひる', 'とんぼ', 'はっぱ', 'ゆびわ', 'なわ', 'たて',
				'おかね', 'プリンアラモード', 'ネックレス', 'いなほ', 'しょうゆ', 'ベルトコンベア', 'シャンデリア', 'しお', 'うずしお', 'つりざお', 'なべ', 'シーソー', 'ふで', 'きんトレ', 'おばけ', 'ヒヨリ', 'ユイ', 'レイ',
				'ミソギ', 'マツリ', 'アカリ', 'ミヤコ', 'ユキ', 'アンナ', 'マホ', 'リノ', 'ハツネ', 'ナナカ', 'カスミ', 'ミサト', 'スズナ', 'カオリ', 'イオ', 'ミミ', 'クルミ', 'ヨリ', 'アヤネ', 'スズメ', 'リン', 'エリコ', 'サレン',
				'ノゾミ', 'ニノン', 'シノブ', 'アキノ', 'マヒル', 'ユカリ', 'キョウカ', 'トモ', 'シオリ', 'アオイ', 'チカ', 'マコト', 'イリヤ', 'クウカ', 'タマキ', 'ジュン', 'ミフユ', 'シズル', 'ミサキ', 'ミツキ', 'リマ', 'モニカ',
				'ツムギ', 'アユミ', 'ルカ', 'ジータ', 'ペコリーヌ', 'コッコロ', 'キャル', 'ムイミ', 'アリサ', 'ネネカ', 'クリスティーナ', 'イノリ', 'カヤ', 'ホマレ', 'クロエ', 'チエル', 'ユニ'
			],
			stickers: [
				'./img/apple_shiritori.webp', './img/gorilla_shiritori.webp', './img/trumpet_shiritori.webp', './img/pineapple_shiritori.webp', './img/ruby_shiritori.webp',
				'./img/beer_shiritori.webp', './img/bow_and_row_shiritori.webp', './img/note_shiritori.webp', './img/paint_shiritori.webp', './img/sword_shiritori.webp',
				'./img/glasses_shiritori.webp', './img/loupe_shiritori.webp', './img/meat_shiritori.webp', './img/moon_shiritori.webp', './img/bat_shiritori.webp',
				'./img/bird_shiritori.webp', './img/shoes_shiritori.webp', './img/cat_shiritori.webp', './img/goldfish_shiritori.webp', './img/mouse_shiritori.webp',
				'./img/egg_shiritori.webp', './img/ship_shiritori.webp', './img/milk_shiritori.webp', './img/chocolate_shiritori.webp', './img/acorn_shiritori.webp',
				'./img/strawberry_shiritori.webp', './img/tiger_shiritori.webp', './img/stuffed_animal_shiritori.webp', './img/bomb_shiritori.webp', './img/watermelon_shiritori.webp',
				'./img/horse_shiritori.webp', './img/chair_shiritori.webp', './img/sea_shiritori.webp', './img/hermit_crab_shiritori.webp', './img/whistle_shiritori.webp',
				'./img/book_shiritori.webp', './img/fish_shiritori.webp', './img/tree_shiritori.webp', './img/candy_shiritori.webp', './img/hammer_shiritori.webp',
				'./img/star_shiritori.webp', './img/hat_shiritori.webp', './img/cup_shiritori.webp', './img/dog_shiritori.webp', './img/flag_shiritori.webp',
				'./img/cake_shiritori.webp', './img/microphone_shiritori.webp', './img/lipstick_shiritori.webp', './img/mochi_shiritori.webp', './img/fairy_shiritori.webp',
				'./img/umbrella_shiritori.webp', './img/dice_shiritori.webp', './img/letter_shiritori.webp', './img/grape_shiritori.webp', './img/sheep_shiritori.webp',
				'./img/tofu_shiritori.webp', './img/duck_shiritori.webp', './img/dragonfly_shiritori.webp', './img/leaf_shiritori.webp', './img/ring_shiritori.webp',
				'./img/rope_shiritori.webp', './img/shield_shiritori.webp', './img/money_shiritori.webp', './img/pudding_shiritori.webp', './img/necklace_shiritori.webp',
				'./img/rice_ear_shiritori.webp', './img/soy_sauce_shiritori.webp', './img/belt_conveyor_shiritori.webp', './img/chandelier_shiritori.webp', './img/salt_shiritori.webp',
				'./img/whirlpool_shiritori.webp', './img/rod_shiritori.webp', './img/pot_shiritori.webp', './img/seesaw_shiritori.webp', './img/brush_shiritori.webp',
				'./img/work_out_shiritori.webp', './img/ghost_shiritori.webp', './img/hiyori_shiritori.webp', './img/yui_shiritori.webp', './img/rei_shiritori.webp',
				'./img/misogi_shiritori.webp', './img/matsuri_shiritori.webp', './img/akari_shiritori.webp', './img/miyako_shiritori.webp', './img/yuki_shiritori.webp',
				'./img/anna_shiritori.webp', './img/maho_shiritori.webp', './img/rino_shiritori.webp', './img/hatsune_shiritori.webp', './img/nanaka_shiritori.webp',
				'./img/kasumi_shiritori.webp', './img/misato_shiritori.webp', './img/suzuna_shiritori.webp', './img/kaori_shiritori.webp', './img/io_shiritori.webp',
				'./img/mimi_shiritori.webp', './img/kurumi_shiritori.webp', './img/yori_shiritori.webp', './img/ayane_shiritori.webp', './img/suzume_shiritori.webp',
				'./img/rin_shiritori.webp', './img/eriko_shiritori.webp', './img/saren_shiritori.webp', './img/nozomi_shiritori.webp', './img/ninon_shiritori.webp',
				'./img/shinobu_shiritori.webp', './img/akino_shiritori.webp', './img/mahiru_shiritori.webp', './img/yukari_shiritori.webp', './img/kyouka_shiritori.webp',
				'./img/tomo_shiritori.webp', './img/shiori_shiritori.webp', './img/aoi_shiritori.webp', './img/chika_shiritori.webp', './img/makoto_shiritori.webp',
				'./img/iriya_shiritori.webp', './img/kuuka_shiritori.webp', './img/tamaki_shiritori.webp', './img/jun_shiritori.webp', './img/mihuyu_shiritori.webp',
				'./img/shizuru_shiritori.webp', './img/misaki_shiritori.webp', './img/mitsuki_shiritori.webp', './img/rima_shiritori.webp', './img/monika_shiritori.webp',
				'./img/tsumugi_shiritori.webp', './img/ayumi_shiritori.webp', './img/ruka_shiritori.webp', './img/jita_shiritori.webp', './img/peko_shiritori.webp',
				'./img/kokkoro_shiritori.webp', './img/kyaru_shiritori.webp', './img/muimi_shiritori.webp', './img/arisa_shiritori.webp', './img/neneka_shiritori.webp',
				'./img/kurisu_shiritori.webp', './img/inori_shiritori.webp', './img/kaya_shiritori.webp', './img/homare_shiritori.webp', './img/kuroe_shiritori.webp',
				'./img/chieru_shiritori.webp', './img/yuni_shiritori.webp'
			]
		};
	},
}
</script>
<style scoped>
</style>
